import React from 'react';

import Head from 'next/head'

import Layout from '@/components/Layout';
import Game from '@/components/Game';
import Header from '@/components/Header';
import Fighters from '@/components/Fighters';

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />
        <Fighters />
        <Game />
      </Layout>
    </>
  )
}
